import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import {
  El_Messiri,
  Montserrat,
  Plus_Jakarta_Sans,
  Poppins,
} from "next/font/google";
import StoreProvider from './_components/dashboard/provider/StoreProvider'

import { Toaster } from "@/components/ui/toaster";
import { TooltipProvider } from "@/components/ui/tooltip";
import { TRPCReactProvider } from "@/trpc/react";
import { Suspense } from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import LoadingPage from "./loading";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});

const el_messeri = El_Messiri({
  subsets: ["latin"],
  variable: "--font-el-messiri",
});

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta-sans",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Kyndom",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "light min-h-screen bg-background font-poppins antialiased",
          poppins.variable,
          el_messeri.variable,
          plusJakartaSans.variable,
          montserrat.variable,
        )}
      >
        <TRPCReactProvider>
          <StoreProvider>
            <Toaster />
            <Suspense fallback={<LoadingPage />}>
              <TooltipProvider>{children}</TooltipProvider>
            </Suspense>
            <ToastContainer />
          </StoreProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
